[google]
type = "service_account"
project_id = "xxxx"
private_key_id = "xxxx"
private_key = "-----BEGIN PRIVATE KEY-----\nXXXX\n-----END PRIVATE KEY-----\n"
client_email = "xxxx@xxxx.iam.gserviceaccount.com"
client_id = "xxxx"
token_uri = "https://oauth2.googleapis.com/token"